'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Adverts',
      [
        {
          title: 'Светлая квартира в центре города',
          body: 'Двухкомнатная квартира с современным ремонтом и большими окнами.',
          userId: 4,
          price: 80000,
          rooms: 2,
          floor: 4,
          square: 70,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Просторная квартира с видом на парк',
          body: 'Трехкомнатная квартира с евроремонтом и панорамными окнами.',
          userId: 2,
          price: 120000,
          rooms: 3,
          floor: 5,
          square: 85,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Квартира с террасой и видом на море',
          body: 'Четырехкомнатная квартира с собственной террасой и прекрасным видом.',
          userId: 3,
          price: 140000,
          rooms: 4,
          floor: 7,
          square: 120,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Современная квартира в новом доме',
          body: 'Двухкомнатная квартира с современным ремонтом и всеми удобствами.',
          userId: 5,
          price: 95000,
          rooms: 2,
          floor: 3,
          square: 65,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Квартира с балконом в центре города',
          body: 'Трехкомнатная квартира с балконом и видом на центральную площадь.',
          userId: 2,
          price: 110000,
          rooms: 3,
          floor: 6,
          square: 90,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Уютный лофт в индустриальном стиле',
          body: 'Двухкомнатная квартира-лофт с высокими потолками и просторной кухней.',
          userId: 3,
          price: 85000,
          rooms: 2,
          floor: 1,
          square: 75,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Квартира с видом на горы',
          body: 'Четырехкомнатная квартира с панорамными окнами и видом на горы.',
          userId: 4,
          price: 130000,
          rooms: 4,
          floor: 8,
          square: 110,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Светлая квартира в зеленом районе',
          body: 'Двухкомнатная квартира с большими окнами и видом на парк.',
          userId: 5,
          price: 70000,
          rooms: 2,
          floor: 2,
          square: 60,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Квартира с террасой и бассейном',
          body: 'Трехкомнатная квартира с собственной террасой и общим бассейном.',
          userId: 2,
          price: 100000,
          rooms: 3,
          floor: 4,
          square: 80,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Квартира с видом на реку',
          body: 'Четырехкомнатная квартира с панорамными окнами и видом на реку.',
          userId: 3,
          price: 145000,
          rooms: 4,
          floor: 9,
          square: 115,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Уютная квартира в тихом районе',
          body: 'Двухкомнатная квартира с уютным интерьером и зеленым двором.',
          userId: 4,
          price: 78000,
          rooms: 2,
          floor: 3,
          square: 68,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Квартира с террасой и гаражом',
          body: 'Трехкомнатная квартира с собственной террасой и гаражом.',
          userId: 5,
          price: 105000,
          rooms: 3,
          floor: 7,
          square: 88,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Современная квартира в элитном доме',
          body: 'Двухкомнатная квартира с высококачественным ремонтом и всеми удобствами.',
          userId: 2,
          price: 90000,
          rooms: 2,
          floor: 6,
          square: 72,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Квартира с террасой и видом на парк',
          body: 'Четырехкомнатная квартира с собственной террасой и зеленым видом.',
          userId: 3,
          price: 135000,
          rooms: 4,
          floor: 5,
          square: 105,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Современная квартира в зеленом районе',
          body: 'Двухкомнатная квартира с современным ремонтом и всеми удобствами.',
          userId: 4,
          price: 88000,
          rooms: 2,
          floor: 4,
          square: 70,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      
      ],
      {},
    );
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
